### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by gwern** [grapeot/Danbooru2018AnimeCharacterRecognitionDataset#1]
> While we also have the cropped face images ready as a tarball, given its size (5.7 GB), we are still not sure where to host it. If you have proper resources, please feel free to open an issue.

I can host it on my rsync server. Send me a download link (preferably something which can be downloaded with wget/rsync/scp so I don't have to reupload it).

**Comment by grapeot** [comment]
Hi Gwern, sorry for the late reply! Just found I didn't set up the notifications correctly so I missed this issue. I've uploaded the tar file here: https://lab.grapeot.me/faceimgs.tar. Please feel free to let me know if you need any additional info!

**Comment by gwern** [comment]
OK, I've got it mirrored:

```
rsync --verbose rsync://78.46.86.149:873/biggan/2019-07-27-grapeot-danbooru2018-animecharacterrecognition.tar ./
```

**Comment by grapeot** [comment]
Thanks a lot Gwern! Will update the README! Appreciate your dataset and hosting!
