### ISSUE TITLE
railgun model

### ISSUE THREAD

**Issue by BZbyr** [grapeot/Danbooru2018AnimeCharacterRecognitionDataset#2]
答主训练好的railgun model能开放下载吗？

**Comment by grapeot** [comment]
抱歉我没太明白。。这个角色是别的数据集我训练了一个baseline model，那个包括了整个数据集里面所有的角色，我还在犹豫是等alignment也做好了，还是现在就放出来。但这不是一个railgun的model。以前的确训练过一个railgun的model，在[这篇文章](https://zhuanlan.zhihu.com/p/57553117)中提到过。你想要的是前面的角色识别的model还是后面的railgun StyleGAN的model呢？

**Comment by BZbyr** [comment]
抱歉，我没有表述清楚，我是看了您知乎专栏过来的，想要的是railgun StyleGAN的model

**Comment by BZbyr** [comment]
想要的是railgun StyleGAN的model

**Comment by BZbyr** [comment]
Sir？

**Comment by grapeot** [comment]
抱歉我现在在外面没有文件的access，我周末给你发一个dropbox的链接哈。

**Comment by grapeot** [comment]
这个是模型的链接：https://www.dropbox.com/s/4fs7ml9jlv3x8ro/network-snapshot-015200.pkl?dl=0
这个是用这个模型生成的角色：https://www.dropbox.com/s/g654m73dsgc2u7d/fakes015200.png?dl=0

**Comment by BZbyr** [comment]
非常感谢！

**Comment by grapeot** [comment]
没事哒！
