### ISSUE TITLE
请问这个数据集还提供下载吗

### ISSUE THREAD

**Issue by ie9ei** [grapeot/Danbooru2018AnimeCharacterRecognitionDataset#4]
想要找一个带标签的动漫人脸数据集进行训练，找到了您的数据集但似乎下载不了了……不知您当前是否还提供其他下载途径呢😭

**Comment by grapeot** [comment]
我看看。这个用百度网盘可以吗？

**Comment by grapeot** [comment]
你是需要原图还是face crop呢？

**Comment by ie9ei** [comment]
> 你是需要原图还是face crop呢？
谢谢你回复消息！！！但我昨天后来找了爱奇艺的iCartoonFace数据集作为替代，暂时可能不需要这个数据集了😗

**Comment by grapeot** [comment]
好的～那我先close了哈～
